### ISSUE TITLE
Topology submission fails due to large size - Request Entity Too Large

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure-Samples/hdinsight-dotnet-java-storm-eventhub#4]
I've followed the instructions and tried to submit the EventHubReader topology to a standard HDInsight Storm cluster version 3.5 (with 36 cores, current standard configuration in the portal). It fails with 'Request Entity Too Large', because the zip file for the topology is about 7 MB. Looks like nginx on cluster has to be reconfigured. 

Detailed submission log:

22.01.2017 14:12:02	ScpC Start: 0 : ScpC Version: 1.0.6127.22663
ScpC Information: 0 : Executing Assembly Path: C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools
ScpC Information: 0 : Executing Assembly's Path Parent: C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1
ScpC Information: 0 : Executing Assembly's Parent's Parent: C:\Dev\stormdev\packages
ScpC Start: 0 : GenerateSpec
ScpC Information: 0 : Load configuration file: C:\Dev\stormdev\EventHubReader\bin\Debug\AzureEventHubsReaderStormApplication.dll.config as default configuartion file.
ScpC Information: 0 : Found active TopologyDescriptor: "EventHubReader.EventHubReader"
ScpC Information: 0 : Generating spec file "C:\Dev\stormdev\EventHubReader\bin\Debug\EventHubReader.spec"
ScpC Information: 0 : Succeed to generate spec file "C:\Dev\stormdev\EventHubReader\bin\Debug\EventHubReader.spec"
22.01.2017 14:12:02	Begin to generate zip package...
22.01.2017 14:12:40	ScpC Start: 0 : ScpC Version: 1.0.6127.22663
ScpC Information: 0 : Executing Assembly Path: C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools
ScpC Information: 0 : Executing Assembly's Path Parent: C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1
ScpC Information: 0 : Executing Assembly's Parent's Parent: C:\Dev\stormdev\packages
ScpC Information: 0 : Create temp folder: C:\Users\jurgenma\AppData\Local\Temp\Temp-ScpC-package-636206875223392586 ...
ScpC Information: 0 : Copy C# files from "C:\Dev\stormdev\EventHubReader\bin\Debug" to resources folder ...
Copying Scp libraries to C:\Users\jurgenma\AppData\Local\Temp\Temp-ScpC-package-636206875223392586\resources
ScpC Information: 0 : Executing Assembly Path: C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools
ScpC Information: 0 : Executing Assembly's Path Parent: C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1
ScpC Information: 0 : Executing Assembly's Parent's Parent: C:\Dev\stormdev\packages
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpC.exe for copying.
ScpC Information: 0 : Copying file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpC.exe to resources C:\Users\jurgenma\AppData\Local\Temp\Temp-ScpC-package-636206875223392586\resources\ScpC.exe.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpC.exe.config for copying.
ScpC Information: 0 : Copying file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpC.exe.config to resources C:\Users\jurgenma\AppData\Local\Temp\Temp-ScpC-package-636206875223392586\resources\ScpC.exe.config.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpWebApiClient.exe for copying.
ScpC Information: 0 : Copying file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpWebApiClient.exe to resources C:\Users\jurgenma\AppData\Local\Temp\Temp-ScpC-package-636206875223392586\resources\ScpWebApiClient.exe.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpWebApiClient.exe.config for copying.
ScpC Information: 0 : Copying file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\tools\ScpWebApiClient.exe.config to resources C:\Users\jurgenma\AppData\Local\Temp\Temp-ScpC-package-636206875223392586\resources\ScpWebApiClient.exe.config.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\log4net.dll for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\log4net.xml for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\Microsoft.SCPNet.dll for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\Microsoft.SCPNet.dll.config for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\Microsoft.SCPNet.XML for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\SCPHost.exe for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\SCPHost.exe.config for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\Thrift.dll for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\Thrift.XML for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Microsoft.SCP.Net.SDK.1.0.0.1\lib\net45\ZooKeeperNet.dll for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Newtonsoft.Json.9.0.1\lib\net45\Newtonsoft.Json.dll for copying.
ScpC Information: 0 : Inspecting file C:\Dev\stormdev\packages\Newtonsoft.Json.9.0.1\lib\net45\Newtonsoft.Json.xml for copying.
ScpC Information: 0 : Copy Java dependencies in "C:\Users\jurgenma\Microsoft\OneDrive - Microsoft\IoT DX\Events\FY17 IoT Ecosystem event Munich\HOL" ...
ScpC Information: 0 : Extract and copy Jar file: "C:\Users\jurgenma\Microsoft\OneDrive - Microsoft\IoT DX\Events\FY17 IoT Ecosystem event Munich\HOL\storm-eventhubs-1.0.2-jar-with-dependencies.jar" ...
ScpC Information: 0 : Extract to: C:\Users\jurgenma\AppData\Local\Temp\Temp-ScpC-jarExtract-636206875226714403 ...
ScpC Information: 0 : Generate zip package file: "C:\Users\jurgenma\AppData\Roaming\Microsoft\HDInsight Tools for Visual Studio\Storm\EventHubReader.zip" ...
ScpC Information: 0 : Succeed to create package "C:\Users\jurgenma\AppData\Roaming\Microsoft\HDInsight Tools for Visual Studio\Storm\EventHubReader.zip"
22.01.2017 14:12:43	Submitting topology ...
22.01.2017 14:12:56	Failed to submit topology :
22.01.2017 14:12:56	StatusCode: RequestEntityTooLarge
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>

**Comment by davidrpk** [comment]
I'm getting the same problem. It's the same issue as https://github.com/hdinsight/hdinsight-storm-examples/issues/11 but in a different package

**Comment by Blackmist** [comment]
@JMayrbaeurl @davidrpk Can you please contact Microsoft support for these problems? These errors are returned from a web service running on the HDInsight cluster, and are not related to this sample.

Thanks

**Comment by davidrpk** [comment]
Thanks, already done.

**Comment by alpajain88** [comment]
facing the same problem when running https://github.com/Azure-Samples/hdinsight-dotnet-java-storm-eventhub
this example . what to do?


2/15/2017 2:51:12 PM	Submitting topology ...
2/15/2017 2:51:18 PM	Failed to submit topology :
2/15/2017 2:51:18 PM	StatusCode: RequestEntityTooLarge
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>

**Comment by Blackmist** [comment]
Hi @alpajain88 this error comes from the web page on the HDInsight cluster, not the example. Please contact Microsoft support services for help with this error.

**Comment by davidrpk** [comment]
Hi @alpajain88, I have spoken to support regarding the issue. They have acknowledged the issue and expect to roll out a fix to the data centers next week.

**Comment by alpajain88** [comment]
Thanks for the quick reply . Also for future can you share the contact details of support

Thanks & Regards,
Alpa
